/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hcl.redhat.sor.message.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7045415195258468618L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"com.hcl.redhat.sor.message.entity\",\"fields\":[{\"name\":\"customerId\",\"type\":\"string\"},{\"name\":\"customerName\",\"type\":\"string\"},{\"name\":\"customerNumber\",\"type\":\"string\"},{\"name\":\"customerEmail\",\"type\":\"string\"},{\"name\":\"customerAddress\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<Customer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Customer to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Customer from a ByteBuffer. */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence customerId;
  @Deprecated public java.lang.CharSequence customerName;
  @Deprecated public java.lang.CharSequence customerNumber;
  @Deprecated public java.lang.CharSequence customerEmail;
  @Deprecated public java.lang.CharSequence customerAddress;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param customerId The new value for customerId
   * @param customerName The new value for customerName
   * @param customerNumber The new value for customerNumber
   * @param customerEmail The new value for customerEmail
   * @param customerAddress The new value for customerAddress
   */
  public Customer(java.lang.CharSequence customerId, java.lang.CharSequence customerName, java.lang.CharSequence customerNumber, java.lang.CharSequence customerEmail, java.lang.CharSequence customerAddress) {
    this.customerId = customerId;
    this.customerName = customerName;
    this.customerNumber = customerNumber;
    this.customerEmail = customerEmail;
    this.customerAddress = customerAddress;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return customerId;
    case 1: return customerName;
    case 2: return customerNumber;
    case 3: return customerEmail;
    case 4: return customerAddress;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: customerId = (java.lang.CharSequence)value$; break;
    case 1: customerName = (java.lang.CharSequence)value$; break;
    case 2: customerNumber = (java.lang.CharSequence)value$; break;
    case 3: customerEmail = (java.lang.CharSequence)value$; break;
    case 4: customerAddress = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'customerName' field.
   * @return The value of the 'customerName' field.
   */
  public java.lang.CharSequence getCustomerName() {
    return customerName;
  }

  /**
   * Sets the value of the 'customerName' field.
   * @param value the value to set.
   */
  public void setCustomerName(java.lang.CharSequence value) {
    this.customerName = value;
  }

  /**
   * Gets the value of the 'customerNumber' field.
   * @return The value of the 'customerNumber' field.
   */
  public java.lang.CharSequence getCustomerNumber() {
    return customerNumber;
  }

  /**
   * Sets the value of the 'customerNumber' field.
   * @param value the value to set.
   */
  public void setCustomerNumber(java.lang.CharSequence value) {
    this.customerNumber = value;
  }

  /**
   * Gets the value of the 'customerEmail' field.
   * @return The value of the 'customerEmail' field.
   */
  public java.lang.CharSequence getCustomerEmail() {
    return customerEmail;
  }

  /**
   * Sets the value of the 'customerEmail' field.
   * @param value the value to set.
   */
  public void setCustomerEmail(java.lang.CharSequence value) {
    this.customerEmail = value;
  }

  /**
   * Gets the value of the 'customerAddress' field.
   * @return The value of the 'customerAddress' field.
   */
  public java.lang.CharSequence getCustomerAddress() {
    return customerAddress;
  }

  /**
   * Sets the value of the 'customerAddress' field.
   * @param value the value to set.
   */
  public void setCustomerAddress(java.lang.CharSequence value) {
    this.customerAddress = value;
  }

  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static com.hcl.redhat.sor.message.entity.Customer.Builder newBuilder() {
    return new com.hcl.redhat.sor.message.entity.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.hcl.redhat.sor.message.entity.Customer.Builder newBuilder(com.hcl.redhat.sor.message.entity.Customer.Builder other) {
    return new com.hcl.redhat.sor.message.entity.Customer.Builder(other);
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.hcl.redhat.sor.message.entity.Customer.Builder newBuilder(com.hcl.redhat.sor.message.entity.Customer other) {
    return new com.hcl.redhat.sor.message.entity.Customer.Builder(other);
  }

  /**
   * RecordBuilder for Customer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private java.lang.CharSequence customerId;
    private java.lang.CharSequence customerName;
    private java.lang.CharSequence customerNumber;
    private java.lang.CharSequence customerEmail;
    private java.lang.CharSequence customerAddress;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hcl.redhat.sor.message.entity.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerName)) {
        this.customerName = data().deepCopy(fields()[1].schema(), other.customerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customerNumber)) {
        this.customerNumber = data().deepCopy(fields()[2].schema(), other.customerNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.customerEmail)) {
        this.customerEmail = data().deepCopy(fields()[3].schema(), other.customerEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customerAddress)) {
        this.customerAddress = data().deepCopy(fields()[4].schema(), other.customerAddress);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hcl.redhat.sor.message.entity.Customer other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerName)) {
        this.customerName = data().deepCopy(fields()[1].schema(), other.customerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customerNumber)) {
        this.customerNumber = data().deepCopy(fields()[2].schema(), other.customerNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.customerEmail)) {
        this.customerEmail = data().deepCopy(fields()[3].schema(), other.customerEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customerAddress)) {
        this.customerAddress = data().deepCopy(fields()[4].schema(), other.customerAddress);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customerId;
    }

    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.customerId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerName() {
      return customerName;
    }

    /**
      * Sets the value of the 'customerName' field.
      * @param value The value of 'customerName'.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder setCustomerName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customerName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerName' field has been set.
      * @return True if the 'customerName' field has been set, false otherwise.
      */
    public boolean hasCustomerName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerName' field.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder clearCustomerName() {
      customerName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerNumber() {
      return customerNumber;
    }

    /**
      * Sets the value of the 'customerNumber' field.
      * @param value The value of 'customerNumber'.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder setCustomerNumber(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.customerNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'customerNumber' field has been set.
      * @return True if the 'customerNumber' field has been set, false otherwise.
      */
    public boolean hasCustomerNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'customerNumber' field.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder clearCustomerNumber() {
      customerNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerEmail() {
      return customerEmail;
    }

    /**
      * Sets the value of the 'customerEmail' field.
      * @param value The value of 'customerEmail'.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder setCustomerEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.customerEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'customerEmail' field has been set.
      * @return True if the 'customerEmail' field has been set, false otherwise.
      */
    public boolean hasCustomerEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'customerEmail' field.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder clearCustomerEmail() {
      customerEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerAddress() {
      return customerAddress;
    }

    /**
      * Sets the value of the 'customerAddress' field.
      * @param value The value of 'customerAddress'.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder setCustomerAddress(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.customerAddress = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'customerAddress' field has been set.
      * @return True if the 'customerAddress' field has been set, false otherwise.
      */
    public boolean hasCustomerAddress() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'customerAddress' field.
      * @return This builder.
      */
    public com.hcl.redhat.sor.message.entity.Customer.Builder clearCustomerAddress() {
      customerAddress = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.customerId = fieldSetFlags()[0] ? this.customerId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.customerName = fieldSetFlags()[1] ? this.customerName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.customerNumber = fieldSetFlags()[2] ? this.customerNumber : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.customerEmail = fieldSetFlags()[3] ? this.customerEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.customerAddress = fieldSetFlags()[4] ? this.customerAddress : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
